// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Ptm
{
    internal sealed partial class Vsix
    {
        public const string Id = "Ptm.b92819ce-69de-4de9-9a94-c3492214d5d7";
        public const string Name = "Pair To MacCatalyst";
        public const string Description = @"Visual Studio 2022 .Net Maui Mac Catalyst Debugger";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Michael Rinderle";
        public const string Tags = "";
    }
}
