// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Ptm
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string PtmString = "5cddb07a-c913-4da6-876f-f187fe5e9e9f";
        public static Guid Ptm = new Guid(PtmString);

        public const string ImageCatalogGuidString = "ae27a6b0-e345-4288-96df-5eaf394ee369";
        public static Guid ImageCatalogGuid = new Guid(ImageCatalogGuidString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int PtmTopLevelMenuGroup = 0x1020;
        public const int PtmTopLevelSubMenuGroup = 0x1021;
        public const int PtmToolbarMenuGroup = 0x1022;
        public const int PtmTopLevelSubMenu = 0x2020;
        public const int PtmToolbarMenu = 0x2021;
        public const int ClearCacheCommand = 0x0300;
        public const int PairToMacCommand = 0x0301;
        public const int OptionsPageCommand = 0x0302;
    }
}